[package]
name = "hdfesse"
version = "0.1.0"
authors = ["Ivan Boldyrev <lispnik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
hdfesse_proto = { path = "../hdfesse_proto" }
libhdfesse = { path = "../libhdfesse" }
structopt = "0.3"
